### ISSUE TITLE
Form Does Not Show

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#3]
Greetings,

I've followed the instruction very closely, but the contact form doesn't show at all. I am using the latest version of GRAV with the Admin plugin and have copied the YAML file appropriately to the user folder.

Suggestions?

**Comment by aradianoff** [comment]
Hello, 

So sorry, the folder name of the repository had a typo and it caused the plugin to not load properly :bow:
Just rename it to `recaptchacontact` and it will work. 

I will contact the GravTeam so that they update it in the gpm too. Thanks a lot for letting me know (I had not seen it because I was cloning the repository directly from GitHub...)

If you have any more problems let me know. :smile:

**Comment by bassplayer7** [comment]
This has been corrected on the official Grav repo: https://github.com/getgrav/grav/issues/253

**Comment by ghost** [comment]
Great! ... Also, it doesn't say in the instruction, but do I copy the Languages folder somewhere too (in order to customize it)?

**Comment by ghost** [comment]
Seems to function now, however I tried both Sendmail and PHP Mailer, neither one worked.
