### ISSUE TITLE
RECAPTCHACONTACT Header in YAML

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#4]
I followed your instructions to create a custom languages.yaml file in the user folder. However, in oder for the site to work and not generate an error I had to add the following line in the header of the file just like the original file in the plugin ...

"RECAPTCHACONTACT:"

So, your example given in the instructions is missing the header (see sample below) ...

RECAPTCHACONTACT:
FORM_LEGEND: "Contact me"                       // Form Legend
    SUBJECT: "New contact from Grav site!"          // Subject for email.
    RECIPIENT: "hello@example.com"            // Email address.

```
FIELDS:                     // Default fields, you can translate the text.
  NAME:
    LABEL: "Name"
    PLACEHOLDER: "Add your name"

  EMAIL:
    LABEL: "Email"
    PLACEHOLDER: "Add your email"

  MESSAGE:
    LABEL: "Message"
    PLACEHOLDER: "Add your message"

  ANTISPAM:
    LABEL: "Antispam"
    PLACEHOLDER: "Please leave this field empty for Antispam"

  SUBMIT:
    LABEL: "Submit"

MESSAGES:                   // Default messages, you can translate the text.
  SUCCESS: "Thank You! Your message has been sent."
  ERROR: "Oops! There was a problem with your submission. Please complete the form and try again."
  FAIL: "Oops! Something went wrong and we couldn't send your message."
```

**Comment by aradianoff** [comment]
Yeah, the example in the instructions is missing the header and the language itself. The user's `languages.yaml` file should have the same structure as the one provided in the plugin (you usually just copy the contents of the file to your custom languages files under the language you want and make the custom modifications, in this and any plugin with language support). I will change the README.md so that the instructions are clearer and have the `RECAPTCHACONTACT:` in them. 

Thanks for letting me know.

**Comment by aradianoff** [comment]
Fixed. The update in instructions will appear in the next plugin release. 
Thanks!

**Comment by ghost** [comment]
All working now! THX!

**Comment by aradianoff** [comment]
Glad to hear it! :+1:
