### ISSUE TITLE
Error after Update

### ISSUE THREAD

**Issue by ghost** [aradianoff/recatpchacontact#6]
See screenshot ... Suggestions?

![screen shot 2015-08-31 at 9 12 01 pm](https://cloud.githubusercontent.com/assets/5008228/9594812/b6a3292a-5025-11e5-962a-f6fdc3095cad.png)

**Comment by aradianoff** [comment]
You need PHP 5.5 or higher for it to work (see README.MD).  I am out of the
computer right now, but if you can't update your php version I will look
into it and tell you how to change the problematic line of code later.

**Comment by aradianoff** [comment]
Since v 1.0.6 [this line in recapthcha.php](https://github.com/aradianoff/recaptchacontact/blob/master/recaptchacontact.php#L61) causes the plugin to depend on php 5.5. Previous versions of PHP will cause the plugin to break. If you have a previous PHP version just substitute the `!empty($this->grav['page'] ->collection())` in [line 61](https://github.com/aradianoff/recaptchacontact/blob/master/recaptchacontact.php#L61) for `$this->grav['page'] ->collection()!=[]`. Future releases of this plugin will already include this change to allow compatibility with the previous versions.

**Comment by aradianoff** [comment]
I just released a new version that I think allows PHP 5.4.

**Comment by ghost** [comment]
I will update and let you know ... THX!

**Comment by ghost** [comment]
The update did not work. Same error.

**Comment by ghost** [comment]
However, once I update to PHP 5.5 all is well :)

**Comment by Tele-Pet** [comment]
I believe I was getting a similar error since updating to GRΛV 0.9.4.0, reCAPTCHA 1.0.7:

```
Whoops\Exception\ErrorException thrown with message "Can't use method return value in write context"

Stacktrace:
#0  in /.../plugins/recaptchacontact/recaptchacontact.php:88
```

Just like @umbergerba, updating PHP to 5.5 (specifically for me, php 5.5 FastCGI) resolved the issue.

**Comment by aradianoff** [comment]
Thanks, Tele-Pet. I had forgot ln.88 used the same expression that gave problems with older PHP versions. I changed that line so that now I think it is really backwards compatible with PHP 5.4 in the next update. :smile:
